# Generated by Django 2.2.4 on 2021-03-22 22:22

import apps.usuarios_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[apps.usuarios_app.utils.mayor_que, apps.usuarios_app.utils.solo_letras])),
                ('apellido', models.CharField(max_length=100, validators=[apps.usuarios_app.utils.mayor_que, apps.usuarios_app.utils.solo_letras])),
                ('correo', models.CharField(max_length=150, validators=[apps.usuarios_app.utils.mayor_que])),
                ('clave', models.CharField(max_length=80)),
                ('confirma_clave', models.CharField(max_length=80)),
                ('desc', models.TextField(blank=True)),
                ('admin', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
